# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print("Numpy Version:", np.__version__)
print("Numpy Configuration:", np.__config__.show())

Numpy Version: 1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/khalo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/khalo/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/khalo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/khalo/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/khalo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/khalo/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/khalo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/User

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.random((2, 3, 5))  

b = np.random.randn(2, 3, 5)

c = np.random.randint(0, 10, (2, 3, 5))


### 4. Print a.


In [4]:
print(a)

[[[0.63270811 0.78963773 0.4278815  0.62966443 0.76463749]
  [0.38215403 0.96489158 0.61542718 0.43596597 0.93734324]
  [0.2857137  0.48816218 0.01537236 0.66686751 0.25992746]]

 [[0.79741701 0.3224159  0.03580893 0.22095074 0.18175439]
  [0.71556334 0.8005728  0.0973873  0.20097778 0.16013734]
  [0.50024853 0.89016617 0.55874934 0.21208021 0.52935461]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
same_size = a.shape == b.shape 
same_size_value = a.size == b.size  
print("Do 'a' and 'b' have the same shape?", same_size)
print("Do 'a' and 'b' have the same size?", same_size_value)

Do 'a' and 'b' have the same shape? False
Do 'a' and 'b' have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [8]:
if same_size:
    result = a + b
    print("Arrays 'a' and 'b' can be added.")
    print(result)
else:
    print("Arrays 'a' and 'b' cannot be added because their shapes are different.")

Arrays 'a' and 'b' cannot be added because their shapes are different.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
c = b.transpose(1, 2, 0) 


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [11]:
d = a + c 


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
print("Array a:\n", a)
print("Array d (a + c):\n", d)

Array a:
 [[[0.63270811 0.78963773 0.4278815  0.62966443 0.76463749]
  [0.38215403 0.96489158 0.61542718 0.43596597 0.93734324]
  [0.2857137  0.48816218 0.01537236 0.66686751 0.25992746]]

 [[0.79741701 0.3224159  0.03580893 0.22095074 0.18175439]
  [0.71556334 0.8005728  0.0973873  0.20097778 0.16013734]
  [0.50024853 0.89016617 0.55874934 0.21208021 0.52935461]]]
Array d (a + c):
 [[[1.63270811 1.78963773 1.4278815  1.62966443 1.76463749]
  [1.38215403 1.96489158 1.61542718 1.43596597 1.93734324]
  [1.2857137  1.48816218 1.01537236 1.66686751 1.25992746]]

 [[1.79741701 1.3224159  1.03580893 1.22095074 1.18175439]
  [1.71556334 1.8005728  1.0973873  1.20097778 1.16013734]
  [1.50024853 1.89016617 1.55874934 1.21208021 1.52935461]]]



### 12. Multiply a and c. Assign the result to e.


In [13]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [14]:
print("Array e (a * c):\n", e)

Array e (a * c):
 [[[0.63270811 0.78963773 0.4278815  0.62966443 0.76463749]
  [0.38215403 0.96489158 0.61542718 0.43596597 0.93734324]
  [0.2857137  0.48816218 0.01537236 0.66686751 0.25992746]]

 [[0.79741701 0.3224159  0.03580893 0.22095074 0.18175439]
  [0.71556334 0.8005728  0.0973873  0.20097778 0.16013734]
  [0.50024853 0.89016617 0.55874934 0.21208021 0.52935461]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 1.964891581728998
Min value in d: 1.0153723592702701
Mean value in d: 1.4839979610011607



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [16]:
f = np.empty_like(d)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [17]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif value > d_min and value < d_mean:
                f[i, j, k] = 25
            elif value > d_mean and value < d_max:
                f[i, j, k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [18]:
print("Array d:\n", d)
print("Array f (labeled values):\n", f)

Array d:
 [[[1.63270811 1.78963773 1.4278815  1.62966443 1.76463749]
  [1.38215403 1.96489158 1.61542718 1.43596597 1.93734324]
  [1.2857137  1.48816218 1.01537236 1.66686751 1.25992746]]

 [[1.79741701 1.3224159  1.03580893 1.22095074 1.18175439]
  [1.71556334 1.8005728  1.0973873  1.20097778 1.16013734]
  [1.50024853 1.89016617 1.55874934 1.21208021 1.52935461]]]
Array f (labeled values):
 [[[ 75.  75.  25.  75.  75.]
  [ 25. 100.  75.  25.  75.]
  [ 25.  75.   0.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]